server:
  port: ${PORT:8083}

spring.application.name: eureka-discovery-service

eureka.client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl.defaultZone: http://${EUREKA_URL:localhost}:${EUREKA_PORT:8083}/eureka