server:
  port: ${PORT:8080}

eureka.client.serviceUrl.defaultZone: http://${EUREKA_URL:localhost}:${EUREKA_PORT:8083}/eureka

spring:
  application.name: api-gateway-service
  cloud.gateway:
    discovery.locator.enabled: true
    routes:
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
          - Path=/v3/api-docs/**
        filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      - id: order-service
        uri: lb://order-service
        predicates:
          - Path=/order/**
        filters:
          - RewritePath=/order/(?<path>.*), /$\{path}
