version: "3"
services:
  eureka:
    build:
      ./eurekaserver
    ports:
      - "8083:8083"
    networks:
      - network-eureka
    environment: 
      - EUREKA_URL=eureka
      - EUREKA_PORT=8083
   
  order-service:
    build: 
      ./order-service
    ports:
      - "8084:8084"
    networks:
      - network-eureka 
    depends_on:
      - eureka
      - db
    environment: 
      - EUREKA_URL=eureka
      - EUREKA_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/orders
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  api-gateway:
    build: 
      ./apigateway
    ports:
      - "8080:8080"
    networks:
      - network-eureka
    depends_on:
      - eureka
      - order-service
    environment: 
      - EUREKA_URL=eureka
      - EUREKA_PORT=8083

  db:
    image: postgres:13.1-alpine
    container_name: db
    networks:
      - network-eureka
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always

networks:
  network-eureka:
    driver: bridge